data_ingestion:
  bucket_name: "my-bucket93441272"
  bucket_file_name: "Hotel_Reservations.csv"
  train_ratio: 0.8
  
data_processing:
  categorical_columns:
    - type_of_meal_plan
    - required_car_parking_space
    - room_type_reserved
    - market_segment_type
    - repeated_guest
    - booking_status

  numerical_columns:
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
  skewness_threshold: 5
  number_of_features: 10
